dist: focal
# language: ruby
# language: minimal
# group: dev

install: skip

script:
- cat /etc/os-release
- uname -a
- sudo systemctl docker restart
- sudo cat /etc/docker/daemon.json
- docker run ubuntu
- docker ps
- ip a
#- systemd-analyze time
#- systemd-analyze blame
