jobs:
  include:
    - os: linux
      dist: trusty
      group: dev
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      group: dev
      script:
        #- sudo apt-get update
        #- sudo apt-get install ca-certificates openssl -y
        #- sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      language: bash
      group: dev
      script:
        #- sudo apt-get update
        #- sudo apt-get install ca-certificates openssl -y
        #- sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: bionic
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal-dev
      group: dev
      script:
        - curl https://asset-packagist.org/packages.json


# dist: xenial
# # language: ruby
# # language: minimal
# # group: dev

# install: skip

# script:
# - sudo cat /etc/ssl/certs/ca-certificates.crt
# - cat /etc/os-release
# - uname -a
# - sudo systemctl restart docker
# - sudo cat /etc/docker/daemon.json
# - docker run ubuntu
# - docker ps
# - ip a
#- systemd-analyze time
#- systemd-analyze blame
