dist: xenial
# language: ruby
# language: minimal
# group: dev

install: skip

script:
- sudo cat /etc/ssl/certs/ca-certificates.crt
# - cat /etc/os-release
# - uname -a
# - sudo systemctl restart docker
# - sudo cat /etc/docker/daemon.json
# - docker run ubuntu
# - docker ps
# - ip a
#- systemd-analyze time
#- systemd-analyze blame
